project_id = "duzbnbugvshgdcaisyyr"

[functions.invite-workspace-member]
verify_jwt = false

[functions.accept-workspace-invitation]
verify_jwt = false

[functions.manage-workspace-members]
verify_jwt = false

[functions.validate-product]
verify_jwt = false

[functions.parse-ingestion]
verify_jwt = false

[functions.run-ingestion-job]
verify_jwt = false

[functions.webhook-ingestion]
verify_jwt = false

[functions.manage-assets]
verify_jwt = false

[functions.extract-pdf-pages]
verify_jwt = false

[functions.vision-parse-pdf]
verify_jwt = false

[functions.map-pdf-to-products]
verify_jwt = false